package com.blackneko.domain.security

enum class Permission {

    PROFILE_READ,
    ADDRESS_MANAGE,
    CATEGORY_MANAGE,

    RESTAURANT_CREATE,
    RESTAURANT_UPDATE,

    PRODUCT_CREATE,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,

    ORDER_CREATE,
    ORDER_READ_OWN,
    ORDER_CANCEL_OWN,

    RESTAURANT_ORDER_READ,
    RESTAURANT_ORDER_UPDATE,

    DRIVER_ORDER_LIST,
    DRIVER_ORDER_ACCEPT,
    DRIVER_ORDER_UPDATE,

    ADMIN_USER_MANAGE,
    ADMIN_RESTAURANT_MANAGE,
    ADMIN_DRIVER_MANAGE
}
