ktor {

    deployment {
        port = 8080
        port = ${?PORT}

        host = "0.0.0.0"
        host = ${?HOST}
    }

    application {
        modules = [
            com.blackneko.ApplicationKt.module
        ]
    }
}

database {

    host = "localhost"
    host = ${?DB_HOST}

    port = 5432
    port = ${?DB_PORT}

    name = "delivery"
    name = ${?DB_NAME}

    user = "delivery"
    user = ${?DB_USER}

    password = ${DB_PASSWORD}

    poolSize = 10
    poolSize = ${?DB_POOL_SIZE}

}


jwt {

    issuer = "delivery-api"
    issuer = ${?JWT_ISSUER}

    audience = "delivery-client"
    audience = ${?JWT_AUDIENCE}

    realm = "Delivery API"
    realm = ${?JWT_REALM}

    secret = ${JWT_SECRET}

    accessTokenExpirationMinutes = 30
    accessTokenExpirationMinutes = ${?JWT_ACCESS_EXPIRATION_MINUTES}

    refreshTokenExpirationDays = 30
    refreshTokenExpirationDays = ${?REFRESH_TOKEN_EXPIRATION_DAYS}
}


cors {

    allowedHosts = "localhost:3000"
    allowedHosts = ${?CORS_ALLOWED_HOSTS}

}

marketplace {
    deliveryFeeCents = 0
    deliveryFeeCents = ${?DELIVERY_FEE_CENTS}
}

http {
    trustProxy = false
    trustProxy = ${?TRUST_PROXY}
}
