ktor {

    deployment {
        port = 8080
        port = ${?PORT}

        host = "0.0.0.0"
        host = ${?HOST}
    }

    application {
        modules = [
            com.blackneko.ApplicationKt.module
        ]
    }
}

database {

    host = "localhost"
    host = ${?DB_HOST}

    port = 5432
    port = ${?DB_PORT}

    name = "delivery"
    name = ${?DB_NAME}

    user = "delivery"
    user = ${?DB_USER}

    password = "delivery123"
    password = ${?DB_PASSWORD}

    poolSize = 10
    poolSize = ${?DB_POOL_SIZE}

}


jwt {

    issuer = "delivery-api"
    issuer = ${?JWT_ISSUER}

    audience = "delivery-client"
    audience = ${?JWT_AUDIENCE}

    secret = "change-me"
    secret = ${?JWT_SECRET}

    expirationMinutes = 60
    expirationMinutes = ${?JWT_EXPIRATION_MINUTES}

}


cors {

    allowedHosts = "localhost:3000"
    allowedHosts = ${?CORS_ALLOWED_HOSTS}

}