package com.blackneko.domain.user

enum class Permission {

    USER_READ,
    USER_UPDATE,

    RESTAURANT_CREATE,
    RESTAURANT_READ,
    RESTAURANT_UPDATE,
    RESTAURANT_DELETE,

    PRODUCT_CREATE,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,

    ORDER_CREATE,
    ORDER_READ,
    ORDER_CANCEL,
    ORDER_UPDATE_STATUS,

    DRIVER_ASSIGN,
    DRIVER_ACCEPT,
    DRIVER_UPDATE_LOCATION
}